# To run locally
# npx @techdocs/cli serve -v -c ./mkdocs.yml
# 
site_name: 'xk6-dashboard Internal Documentation'
repo_url: https://github.com/grafana/xk6-dashboard
edit_uri: edit/main/docs

theme:
  name: material
  features:
    - navigation.sections

plugins:
  - techdocs-core
